### ISSUE TITLE
Redirect to order confirmation instead of empty cart page after payment

### ISSUE THREAD

**Issue by toxis** [payrexx/prestashop-payrexx-gateway#21]
Hello,

I have installed the last version of plugin (1.4.8) in PrestaShop 8.1.4.
I have successfully configured the plugin (for the moment my Payrexx account is in test mode) and can pay with Payrexx.

But after the payment, Payrexx redirects to cart page (that is empty after payment) instead of confirmation page.

Is it possible to configure it so that it redirects to order confirmation page?

**Comment by PayrexxIntegration** [comment]
Hello     It seems like your webhooks are not set up the right way. Can you please check your configuration and try it again?     I hope this helps.     Kind Regards,  Ugur                
                           
                            On
                            Tue, 19 Mar at  1:51 PM
                            ,  payrexx/prestashop-payrexx-gateway ***@***.***>  wrote:
                             
 Hi, 
 Here the screen recording: 
https://www.swisstransfer.com/d/70862ca7-3ecb-4473-82fc-d78344e0366f
 
 You can go to 00:01:00 to view the payment process.

**Comment by toxis** [comment]
Thank you for your feedback Ugur.

So I received a 500 error from Payrexx module gateway, here the log from Payrexx backoffice:

URI
`https://prestashop.foodsystem.ch/module/payrexx/gateway`

Header
```
POST /module/payrexx/gateway HTTP/1.1
Host: prestashop.foodsystem.ch
User-Agent: Payrexx Webhook
Accept: */*
Content-Type: application/x-www-form-urlencoded
Content-Length: 4401
Expect: 100-continue
```

HTTP Status
`500`

And here the log from PrestaShop (advanced parameters > logs):

`Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart`

Any idea where I can have more information about the 500 error or check the configuration?

**Comment by PayrexxIntegration** [comment]
Hello again,     This should not be the case. We created a bug ticket to debug the issue and get a more explanatory error message.  I am sorry for the inconvenience. I will inform you as soon as I get feedback on the issue.     Kind Regards,  Ugur              
                           
                            On
                            Wed, 20 Mar at 12:06 PM
                            ,  payrexx/prestashop-payrexx-gateway ***@***.***>  wrote:
                             
 Thank you for your feedback Ugur. 
 So I received a 500 error from Payrexx module gateway, here the log from Payrexx backoffice: 
 URI 
https://prestashop.foodsystem.ch/module/payrexx/gateway
 
 Header 
 POST /module/payrexx/gateway HTTP/1.1
Host: prestashop.foodsystem.ch
User-Agent: Payrexx Webhook
Accept: */*
Content-Type: application/x-www-form-urlencoded
Content-Length: 4401
Expect: 100-continue
 
 HTTP Status 
500
 
 And here the log from PrestaShop (advanced parameters > logs): 
 Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart 
 Any idea where I can have more information about the 500 error or check the configuration?

**Comment by PayrexxIntegration** [comment]
Hello     Can you please update the plugin and try the same process again? So that we get a new webhook that we can analyze.     Thanks in advance.     Kind Regards,  Ugur                On Wed, 20 Mar at 12:26 PM , Payrexx Integration Support ***@***.***> wrote:    Hello again,     This should not be the case. We created a bug ticket to debug the issue and get a more explanatory error message.  I am sorry for the inconvenience. I will inform you as soon as I get feedback on the issue.     Kind Regards,  Ugur               On Wed, 20 Mar at 12:06 PM , payrexx/prestashop-payrexx-gateway ***@***.***> wrote:   Thank you for your feedback Ugur.  So I received a 500 error from Payrexx module gateway, here the log from Payrexx backoffice:  URI https://prestashop.foodsystem.ch/module/payrexx/gateway  Header  POST /module/payrexx/gateway HTTP/1.1 Host: prestashop.foodsystem.ch User-Agent: Payrexx Webhook Accept: */* Content-Type: application/x-www-form-urlencoded Content-Length: 4401 Expect: 100-continue   HTTP Status 500  And here the log from PrestaShop (advanced parameters > logs):  Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart  Any idea where I can have more information about the 500 error or check the configuration?  — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by toxis** [comment]
Hi Ugur,

Thanks for your reply.

I haven't found a new version to update the plugin (I'm using version 1.4.8).
I have redone the same payment process.

Regards

**Comment by toxis** [comment]
Hello,

Do you need additional information from me to analyze this issue?

**Comment by toxis** [comment]
Some news: it seems that this problem occurs when SMTP is not configured in PrestaShop.

I'm closing this issue and will reopen it if necessary.
